name: 'trufflehog3 Actions Scan'
description: 'Scan repository for secrets'
author: 'CloudTeam'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  scanArguments:
    description: 'Argument options for scan.'
    required: false
branding:
  icon: 'shield'
  color: 'yellow'
